export default {
   'pt': {
      'Yes': 'Sim',
      'No': 'Não',
      'Cancel': 'Cancelar',
      'Clear': 'Limpar',
      'Done': 'Feito',
      'Loading': 'Carregando...',
      'Select': 'Selecionar...',
      'Search': 'Procurar',
      'Back': 'Voltar',
      'OK': 'OK',

      'dxCollectionWidget-noDataText': '(Sem dados)',

      'validation-required': 'Requerido',
      'validation-required-formatted': '{0} é requerido',
      'validation-numeric': 'Valor deve ser numérico',
      'validation-numeric-formatted': '{0} deve ser numérico',
      'validation-range': 'Valor está fora do intervalo',
      'validation-range-formatted': '{0} está fora do intervalo',
      'validation-stringLength': 'A quantidade de caracteres não está correta',
      'validation-stringLength-formatted': 'A quantidade de caracteres de {0} não está correta',
      'validation-custom': 'Valor não é válido',
      'validation-custom-formatted': '{0} é inválido',
      'validation-compare': 'Valor não é igual',
      'validation-compare-formatted': '{0} não é igual',
      'validation-pattern': 'Valor está fora do formato padrão',
      'validation-pattern-formatted': '{0} está fora do formato padrão',
      'validation-email': 'E-mail inválido',
      'validation-email-formatted': '{0} inválido',
      'validation-mask': 'Valor inválido',

      'dxLookup-searchPlaceholder': 'Número mínimo de caracteres: {0}',

      'dxList-pullingDownText': 'Puxe para atualizar...',
      'dxList-pulledDownText': 'Solte para atualizar...',
      'dxList-refreshingText': 'Atualizando...',
      'dxList-pageLoadingText': 'Carregando...',
      'dxList-nextButtonText': 'Mais',
      'dxList-selectAll': 'Selecionar todos',
      'dxListEditDecorator-delete': 'Deletar',
      'dxListEditDecorator-more': 'Mais',

      'dxScrollView-pullingDownText': 'Puxe para atualizar...',
      'dxScrollView-pulledDownText': 'Solte para atualizar...',
      'dxScrollView-refreshingText': 'Atualizando...',
      'dxScrollView-reachBottomText': 'Carregando...',

      'dxDateBox-simulatedDataPickerTitleTime': 'Selecione o hora',
      'dxDateBox-simulatedDataPickerTitleDate': 'Selecione a data',
      'dxDateBox-simulatedDataPickerTitleDateTime': 'Seleciona data e hora',
      'dxDateBox-validation-datetime': 'Valor deve ser uma data ou um horário',

      'dxFileUploader-selectFile': 'Selecionar arquivo',
      'dxFileUploader-dropFile': 'ou soltar arquivo aqui',
      'dxFileUploader-bytes': 'bytes',
      'dxFileUploader-kb': 'kb',
      'dxFileUploader-Mb': 'Mb',
      'dxFileUploader-Gb': 'Gb',
      'dxFileUploader-upload': 'Upload',
      'dxFileUploader-uploaded': 'Uploaded',
      'dxFileUploader-readyToUpload': 'Pronto para upload',
      'dxFileUploader-uploadFailedMessage': 'Upload falhou',

      'dxRangeSlider-ariaFrom': 'From',
      'dxRangeSlider-ariaTill': 'Till',

      'dxSwitch-onText': 'ON',
      'dxSwitch-offText': 'OFF',

      'dxForm-optionalMark': 'opcional',
      'dxForm-requiredMessage': '{0} é requerido',

      'dxNumberBox-invalidValueMessage': 'Valor deve ser numeral',

      'dxDataGrid-columnChooserTitle': 'Escolher Coluna',
      'dxDataGrid-columnChooserEmptyText': 'Arraste a coluna aqui',
      'dxDataGrid-groupContinuesMessage': 'Continua na próxima página',
      'dxDataGrid-groupContinuedMessage': 'Continua da página anterior',
      'dxDataGrid-groupHeaderText': 'Agrupar por essa coluna',
      'dxDataGrid-ungroupHeaderText': 'Desagrupar',
      'dxDataGrid-ungroupAllText': 'Desagrupar Todos',
      'dxDataGrid-editingEditRow': 'Editar',
      'dxDataGrid-editingSaveRowChanges': 'Salvar',
      'dxDataGrid-editingCancelRowChanges': 'Cancelar',
      'dxDataGrid-editingDeleteRow': 'Deletar',
      'dxDataGrid-editingUndeleteRow': 'Desfazer',
      'dxDataGrid-editingConfirmDeleteMessage': 'Você tem certeza que deseja deletar esse registro?',
      'dxDataGrid-validationCancelChanges': 'Cancelar alterações',
      'dxDataGrid-groupPanelEmptyText': 'Solte uma coluna aqui para agrupar.',
      'dxDataGrid-noDataText': 'Sem dados',
      'dxDataGrid-searchPanelPlaceholder': 'Procurar...',
      'dxDataGrid-filterRowShowAllText': '(Todos)',
      'dxDataGrid-filterRowResetOperationText': 'Resetar',
      'dxDataGrid-filterRowOperationEquals': 'Igual',
      'dxDataGrid-filterRowOperationNotEquals': 'Não é igual',
      'dxDataGrid-filterRowOperationLess': 'Menor que',
      'dxDataGrid-filterRowOperationLessOrEquals': 'Menor ou igual a',
      'dxDataGrid-filterRowOperationGreater': 'Maior que',
      'dxDataGrid-filterRowOperationGreaterOrEquals': 'Maior ou igual a',
      'dxDataGrid-filterRowOperationStartsWith': 'Começa com',
      'dxDataGrid-filterRowOperationContains': 'Contêm',
      'dxDataGrid-filterRowOperationNotContains': 'Não contêm',
      'dxDataGrid-filterRowOperationEndsWith': 'Termina com',
      'dxDataGrid-filterRowOperationBetween': 'Entre',
      'dxDataGrid-filterRowOperationBetweenStartText': 'Início',
      'dxDataGrid-filterRowOperationBetweenEndText': 'Fim',
      'dxDataGrid-applyFilterText': 'Aplicar filtro',
      'dxDataGrid-trueText': 'sim',
      'dxDataGrid-falseText': 'não',
      'dxDataGrid-sortingAscendingText': 'Order cescente',
      'dxDataGrid-sortingDescendingText': 'Ordenar decrescente',
      'dxDataGrid-sortingClearText': 'Limpar ordenação',
      'dxDataGrid-editingSaveAllChanges': 'Salvar alterações',
      'dxDataGrid-editingCancelAllChanges': 'Descartar alterações',
      'dxDataGrid-editingAddRow': 'Adicionar uma linha',
      'dxDataGrid-summaryMin': 'Mínimo: {0}',
      'dxDataGrid-summaryMinOtherColumn': 'Min of {1} is {0}',
      'dxDataGrid-summaryMax': 'Máximo: {0}',
      'dxDataGrid-summaryMaxOtherColumn': 'Max of {1} is {0}',
      'dxDataGrid-summaryAvg': 'Média: {0}',
      'dxDataGrid-summaryAvgOtherColumn': 'Média de {1} é {0}',
      'dxDataGrid-summarySum': 'Soma: {0}',
      'dxDataGrid-summarySumOtherColumn': 'Soma de {1} é {0}',
      'dxDataGrid-summaryCount': 'Quantidade: {0}',
      'dxDataGrid-columnFixingFix': 'Fixar',
      'dxDataGrid-columnFixingUnfix': 'Desfixar',
      'dxDataGrid-columnFixingLeftPosition': 'A esquerda',
      'dxDataGrid-columnFixingRightPosition': 'A direita',
      'dxDataGrid-exportTo': 'Exportar',
      'dxDataGrid-exportToExcel': 'Exportar para Excel',
      'dxDataGrid-excelFormat': 'Arquivo Excel',
      'dxDataGrid-selectedRows': 'Selecionar linhar',
      'dxDataGrid-exportSelectedRows': 'Exportar linhas selecionadas',
      'dxDataGrid-exportAll': 'Exportar todos os dados',
      'dxDataGrid-headerFilterEmptyValue': '(Em branco)',
      'dxDataGrid-headerFilterOK': 'OK',
      'dxDataGrid-headerFilterCancel': 'Cancelar',
      'dxDataGrid-ariaColumn': 'Coluna',
      'dxDataGrid-ariaValue': 'Valor',
      'dxDataGrid-ariaFilterCell': 'Filtrar célular',
      'dxDataGrid-ariaCollapse': 'Comprimir',
      'dxDataGrid-ariaExpand': 'Expandir',
      'dxDataGrid-ariaDataGrid': 'Data grid',
      'dxDataGrid-ariaSearchInGrid': 'Procurar na lista',
      'dxDataGrid-ariaSelectAll': 'Selecionar todos',
      'dxDataGrid-ariaSelectRow': 'Selecionar linha',

      'dxTreeList-ariaTreeList': 'Árvore',
      'dxTreeList-editingAddRowToNode': 'Adicionar',

      'dxPager-infoText': 'Página {0} de {1} ({2} items)',
      'dxPager-pagesCountText': 'de',

      'dxPivotGrid-grandTotal': 'Total',
      'dxPivotGrid-total': '{0} Total',
      'dxPivotGrid-fieldChooserTitle': 'Escolher Campos',
      'dxPivotGrid-showFieldChooser': 'Mostrar Escolher Campos',
      'dxPivotGrid-expandAll': 'Expandir tudo',
      'dxPivotGrid-collapseAll': 'Comprimir tudo',
      'dxPivotGrid-sortColumnBySummary': 'Ordenar \'{0}\' por essa coluna',
      'dxPivotGrid-sortRowBySummary': 'Ordenar \'{0}\' por essa linha',
      'dxPivotGrid-removeAllSorting': 'Remover ordenações',
      'dxPivotGrid-dataNotAvailable': 'N/A',
      'dxPivotGrid-rowFields': 'Campos de linha',
      'dxPivotGrid-columnFields': 'Campos de coluna',
      'dxPivotGrid-dataFields': 'Campos de data',
      'dxPivotGrid-filterFields': 'Campos de filtro',
      'dxPivotGrid-allFields': 'Todos os campos',
      'dxPivotGrid-columnFieldArea': 'Solte as colunas aqui',
      'dxPivotGrid-dataFieldArea': 'Solte os campos aqui',
      'dxPivotGrid-rowFieldArea': 'Solte as linhas aqui',
      'dxPivotGrid-filterFieldArea': 'Solte os filtros aqui',

      'dxScheduler-editorLabelTitle': 'Assunto',
      'dxScheduler-editorLabelStartDate': 'Data inicial',
      'dxScheduler-editorLabelEndDate': 'Data final',
      'dxScheduler-editorLabelDescription': 'Descrição',
      'dxScheduler-editorLabelRecurrence': 'Repetir',

      'dxScheduler-openAppointment': 'Abrir compromisso',

      'dxScheduler-recurrenceNever': 'Nunca',
      'dxScheduler-recurrenceDaily': 'Diário',
      'dxScheduler-recurrenceWeekly': 'Semanal',
      'dxScheduler-recurrenceMonthly': 'Mensagel',
      'dxScheduler-recurrenceYearly': 'Anual',

      'dxScheduler-recurrenceEvery': 'Todo',
      'dxScheduler-recurrenceEnd': 'Até',
      'dxScheduler-recurrenceAfter': 'Depois',
      'dxScheduler-recurrenceOn': 'Em',

      'dxScheduler-recurrenceRepeatDaily': 'dia(s)',
      'dxScheduler-recurrenceRepeatWeekly': 'semana(s)',
      'dxScheduler-recurrenceRepeatMonthly': 'mês(es)',
      'dxScheduler-recurrenceRepeatYearly': 'ano(s)',

      'dxScheduler-switcherDay': 'Dia',
      'dxScheduler-switcherWeek': 'Semana',
      'dxScheduler-switcherWorkWeek': 'Dia úteis',
      'dxScheduler-switcherMonth': 'Mês',

      'dxScheduler-switcherAgenda': 'Agenda',

      'dxScheduler-switcherTimelineDay': 'Timeline Dia',
      'dxScheduler-switcherTimelineWeek': 'Timeline Semana',
      'dxScheduler-switcherTimelineWorkWeek': 'Timeline Dias úteis',
      'dxScheduler-switcherTimelineMonth': 'Timeline Mês',

      'dxScheduler-recurrenceRepeatOnDate': 'na data',
      'dxScheduler-recurrenceRepeatCount': 'ocorência(s)',
      'dxScheduler-allDay': 'Todos os dias',

      'dxScheduler-confirmRecurrenceEditMessage': 'Você desejar editar somente este compromisso ou toda a série?',
      'dxScheduler-confirmRecurrenceDeleteMessage': 'Você desejar deletar somente este compromisso ou toda a série?',

      'dxScheduler-confirmRecurrenceEditSeries': 'Editar séries',
      'dxScheduler-confirmRecurrenceDeleteSeries': 'Deletar séries',
      'dxScheduler-confirmRecurrenceEditOccurrence': 'Editar compromisso',
      'dxScheduler-confirmRecurrenceDeleteOccurrence': 'Deletar compromisso',

      'dxScheduler-noTimezoneTitle': 'Sem timezone',

      'dxCalendar-todayButtonText': 'Hoje',
      'dxCalendar-ariaWidgetName': 'Calendário',

      'dxColorView-ariaRed': 'Vermelho',
      'dxColorView-ariaGreen': 'Verde',
      'dxColorView-ariaBlue': 'Azul',
      'dxColorView-ariaAlpha': 'Transparente',
      'dxColorView-ariaHex': 'Código da cor',

      'vizExport-printingButtonText': 'Imprimir',
      'vizExport-titleMenuText': 'Exportando/Imprimindo',
      'vizExport-exportButtonText': '{0} arquivo'
   }
};
